// Drivers
export const SAVE_DRIVERS_POSITIONS = 'SAVE_DRIVERS_POSITIONS';
export const SELECT_DRIVERS_CLOSE_TO_ORDER = 'SELECT_DRIVERS_CLOSE_TO_ORDER';

// Orders
export const SAVE_ORDERS = 'SAVE_ORDERS';
export const SELECT_ORDER = 'SELECT_ORDER';

